services:
  - type: web
    name: anukriti-core
    env: docker
    region: ohio
    plan: free
    dockerContext: ./anukriti-core
    dockerfilePath: ./anukriti-core/Dockerfile
    healthCheckPath: /
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: MESHY_API_KEY
        sync: false
