"""
Anukriti Numerical Simulation Engine
Runs actual physics-based simulations using numpy.
Supports: electrical circuits, thermal analysis, battery discharge, fluid dynamics.
"""

import time
from dataclasses import asdict, dataclass, field
from typing import Any, Dict, List

import numpy as np


@dataclass
class SimulationConfig:
    """Configuration generated by LLM for what to simulate."""

    device_name: str = "Medical Device"
    duration: float = 10.0  # seconds
    time_steps: int = 500
    models: List[Dict[str, Any]] = field(default_factory=list)
    # Each model: {"type": "battery"|"thermal"|"electrical"|"flow"|"signal",
    #              "params": {...}, "name": "..."}


@dataclass
class SimulationResult:
    """Structured simulation output with real computed data."""

    status: str = "completed"
    duration_seconds: float = 0.0
    time_array: List[float] = field(default_factory=list)
    channels: Dict[str, Dict[str, Any]] = field(default_factory=dict)
    # channels = { "battery_voltage": {"values": [...], "unit": "V", "min": x, "max": y, "mean": z} }
    metrics: Dict[str, float] = field(default_factory=dict)
    warnings: List[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return asdict(self)


class NumericalEngine:
    """Runs actual physics simulations using numpy."""

    def run(self, config: SimulationConfig) -> SimulationResult:
        start_time = time.time()
        t = np.linspace(0, config.duration, config.time_steps)
        result = SimulationResult(time_array=t.tolist())

        for model in config.models:
            model_type = model.get("type", "")
            model_name = model.get("name", model_type)
            params = model.get("params", {})

            try:
                if model_type == "battery_discharge":
                    self._sim_battery(t, params, model_name, result)
                elif model_type == "thermal":
                    self._sim_thermal(t, params, model_name, result)
                elif model_type == "electrical_circuit":
                    self._sim_rc_circuit(t, params, model_name, result)
                elif model_type == "fluid_flow":
                    self._sim_fluid_flow(t, params, model_name, result)
                elif model_type == "signal_response":
                    self._sim_signal_response(t, params, model_name, result)
                elif model_type == "motor_drive":
                    self._sim_motor(t, params, model_name, result)
                elif model_type == "sensor_noise":
                    self._sim_sensor(t, params, model_name, result)
                elif model_type == "leakage_current":
                    self._sim_leakage(t, params, model_name, result)
                else:
                    result.warnings.append(f"Unknown model type: {model_type}")
            except Exception as e:
                result.warnings.append(f"Model '{model_name}' failed: {str(e)}")

        result.duration_seconds = round(time.time() - start_time, 3)
        return result

    def _add_channel(
        self, result: SimulationResult, name: str, values: np.ndarray, unit: str
    ):
        """Add a computed channel to results. Sanitizes NaN/Inf to prevent JSON errors."""
        # Sanitize the array — replace NaN/Inf with 0.0 so JSON serialization never crashes
        safe_values = np.nan_to_num(values, nan=0.0, posinf=0.0, neginf=0.0)
        result.channels[name] = {
            "values": safe_values.tolist(),
            "unit": unit,
            "min": round(float(np.min(safe_values)), 4),
            "max": round(float(np.max(safe_values)), 4),
            "mean": round(float(np.mean(safe_values)), 4),
            "std": round(float(np.std(safe_values)), 4),
        }
        result.metrics[f"{name}_max"] = round(float(np.max(safe_values)), 4)
        result.metrics[f"{name}_min"] = round(float(np.min(safe_values)), 4)

    # ─── Battery Discharge Model ────────────────────────
    def _sim_battery(
        self, t: np.ndarray, params: dict, name: str, result: SimulationResult
    ):
        """
        Realistic battery discharge curve using modified Shepherd model.
        V(t) = V0 - R*I - K*(Q/(Q-It)) * It + A*exp(-B*It)
        """
        V0 = params.get("nominal_voltage", 3.7)  # Volts (Li-ion typical)
        capacity_ah = params.get("capacity_ah", 2.0)  # Amp-hours
        load_current = params.get("load_current", 0.5)  # Amps
        R_internal = params.get("internal_resistance", 0.05)  # Ohms

        K = params.get("polarization_constant", 0.1)  # Polarization voltage
        A = params.get("exponential_amplitude", 0.3)  # Exponential zone amplitude
        B = params.get("exponential_decay", 3.0)  # Exponential zone decay

        Q = capacity_ah * 3600  # Convert to coulombs
        I = load_current
        It = I * t  # Charge consumed

        # Prevent division by zero near full discharge
        safe_denom = np.maximum(Q - It, Q * 0.01)

        voltage = (
            V0
            - R_internal * I
            - K * (Q / safe_denom) * It / Q
            + A * np.exp(-B * It / Q)
        )
        voltage = np.clip(voltage, 0, V0 + 0.5)

        # State of charge
        soc = np.clip(1.0 - It / Q, 0, 1) * 100

        # Power
        power = voltage * I

        self._add_channel(result, f"{name}_voltage", voltage, "V")
        self._add_channel(result, f"{name}_soc", soc, "%")
        self._add_channel(result, f"{name}_power", power, "W")

        # Calculate estimated battery life
        life_hours = capacity_ah / load_current
        result.metrics[f"{name}_estimated_life_hours"] = round(life_hours, 2)

    # ─── Thermal Model ──────────────────────────────────
    def _sim_thermal(
        self, t: np.ndarray, params: dict, name: str, result: SimulationResult
    ):
        """
        Newton's law of cooling/heating with power dissipation.
        dT/dt = (P - h*A*(T - T_ambient)) / (m * Cp)
        Solved using Euler method.
        """
        T_ambient = params.get("ambient_temp", 25.0)  # °C
        T_initial = params.get("initial_temp", 25.0)  # °C
        power_dissipation = params.get("power_watts", 2.0)  # Watts
        thermal_mass = params.get("thermal_mass", 50.0)  # J/°C (m * Cp)
        h_A = params.get("heat_transfer_coeff", 0.5)  # W/°C (h * surface_area)
        max_temp = params.get("max_safe_temp", 45.0)  # °C safety limit

        dt = t[1] - t[0] if len(t) > 1 else 0.01
        T = np.zeros_like(t)
        T[0] = T_initial

        for i in range(1, len(t)):
            dTdt = (power_dissipation - h_A * (T[i - 1] - T_ambient)) / thermal_mass
            T[i] = T[i - 1] + dTdt * dt

        self._add_channel(result, f"{name}_temperature", T, "°C")

        # Check safety
        if np.max(T) > max_temp:
            result.warnings.append(
                f"⚠️ THERMAL WARNING: {name} exceeds {max_temp}°C (peak: {np.max(T):.1f}°C)"
            )
        result.metrics[f"{name}_peak_temp"] = round(float(np.max(T)), 2)
        result.metrics[f"{name}_steady_state_temp"] = round(float(T[-1]), 2)

    # ─── RC Circuit Model ───────────────────────────────
    def _sim_rc_circuit(
        self, t: np.ndarray, params: dict, name: str, result: SimulationResult
    ):
        """
        RC circuit response: V(t) = Vs * (1 - exp(-t/RC)) for step input.
        Also computes current I(t) = (Vs/R) * exp(-t/RC).
        """
        Vs = params.get("supply_voltage", 5.0)  # V
        R = params.get("resistance", 1000.0)  # Ohms
        C = params.get("capacitance", 0.001)  # Farads

        tau = R * C  # Time constant
        V_cap = Vs * (1 - np.exp(-t / tau))
        I_circuit = (Vs / R) * np.exp(-t / tau)
        P_resistor = I_circuit**2 * R

        self._add_channel(result, f"{name}_voltage", V_cap, "V")
        self._add_channel(result, f"{name}_current", I_circuit * 1000, "mA")  # in mA
        self._add_channel(result, f"{name}_power_dissipation", P_resistor * 1000, "mW")

        result.metrics[f"{name}_time_constant_ms"] = round(tau * 1000, 4)
        result.metrics[f"{name}_settling_time_ms"] = round(5 * tau * 1000, 4)

    # ─── Fluid Flow (Infusion Pump) ─────────────────────
    def _sim_fluid_flow(
        self, t: np.ndarray, params: dict, name: str, result: SimulationResult
    ):
        """
        Peristaltic pump flow model with pulsation and occlusion detection.
        Q(t) = Q_nominal * pump_efficiency * (1 + pulsation * sin(2π * rpm * t / 60))
        """
        flow_rate_mlh = params.get("flow_rate_ml_per_hour", 10.0)
        rpm = params.get("pump_rpm", 30.0)
        pulsation = params.get("pulsation_index", 0.15)
        efficiency = params.get("pump_efficiency", 0.92)
        reservoir_ml = params.get("reservoir_volume_ml", 100.0)

        Q_base = flow_rate_mlh / 3600  # ml/s
        Q = Q_base * efficiency * (1 + pulsation * np.sin(2 * np.pi * rpm * t / 60))
        Q = np.clip(Q, 0, None)

        # Cumulative volume delivered
        dt = t[1] - t[0] if len(t) > 1 else 0.01
        volume_delivered = np.cumsum(Q) * dt
        remaining = np.clip(reservoir_ml - volume_delivered, 0, reservoir_ml)

        # Pressure (simplified — higher pressure when flow is occluded)
        pressure = params.get("line_pressure_mmhg", 50.0) + 10 * np.sin(
            2 * np.pi * rpm * t / 60
        )
        noise = np.random.normal(0, 1.5, len(t))
        pressure = pressure + noise

        self._add_channel(result, f"{name}_flow_rate", Q * 3600, "mL/h")
        self._add_channel(result, f"{name}_volume_delivered", volume_delivered, "mL")
        self._add_channel(result, f"{name}_reservoir_remaining", remaining, "mL")
        self._add_channel(result, f"{name}_line_pressure", pressure, "mmHg")

        life_hours = reservoir_ml / flow_rate_mlh
        result.metrics[f"{name}_reservoir_life_hours"] = round(life_hours, 2)

    # ─── Signal Response (ADC / Sensor readout) ─────────
    def _sim_signal_response(
        self, t: np.ndarray, params: dict, name: str, result: SimulationResult
    ):
        """
        Sensor signal with noise, drift, and filtering.
        """
        signal_freq = params.get("signal_frequency_hz", 1.0)
        amplitude = params.get("amplitude", 1.0)
        offset = params.get("dc_offset", 0.0)
        noise_std = params.get("noise_amplitude", 0.05)
        drift_rate = params.get("drift_rate", 0.001)  # per second
        adc_bits = params.get("adc_resolution_bits", 12)

        # Clean signal
        clean = amplitude * np.sin(2 * np.pi * signal_freq * t) + offset

        # Add drift
        drift = drift_rate * t

        # Add noise
        noise = np.random.normal(0, noise_std, len(t))
        raw_signal = clean + drift + noise

        # ADC quantization
        adc_levels = 2**adc_bits
        v_range = params.get("adc_range_v", 3.3)
        quantized = np.round(raw_signal / v_range * adc_levels) * v_range / adc_levels

        # SNR
        signal_power = np.mean(clean**2)
        noise_power = np.mean(noise**2)
        snr_db = 10 * np.log10(signal_power / noise_power) if noise_power > 0 and signal_power > 0 else 0.0
        snr_db = float(np.nan_to_num(snr_db, nan=0.0, posinf=0.0, neginf=0.0))

        self._add_channel(result, f"{name}_raw_signal", raw_signal, "V")
        self._add_channel(result, f"{name}_quantized", quantized, "V")
        result.metrics[f"{name}_snr_db"] = round(float(snr_db), 2)

    # ─── Motor Drive ────────────────────────────────────
    def _sim_motor(
        self, t: np.ndarray, params: dict, name: str, result: SimulationResult
    ):
        """
        DC motor step response: first-order with back-EMF.
        dω/dt = (V - Ke*ω) / (R*J/(Kt)) - (B/J)*ω
        """
        V_supply = params.get("supply_voltage", 12.0)
        R_motor = params.get("resistance", 2.0)  # Ohms
        Kt = params.get("torque_constant", 0.05)  # Nm/A
        Ke = params.get("back_emf_constant", 0.05)  # V/(rad/s)
        J = params.get("inertia", 0.001)  # kg*m^2
        B = params.get("damping", 0.0005)  # Nm/(rad/s)

        dt = t[1] - t[0] if len(t) > 1 else 0.01
        omega = np.zeros_like(t)
        current = np.zeros_like(t)

        for i in range(1, len(t)):
            emf = Ke * omega[i - 1]
            current[i] = (V_supply - emf) / R_motor
            torque = Kt * current[i] - B * omega[i - 1]
            omega[i] = omega[i - 1] + (torque / J) * dt

        rpm = omega * 60 / (2 * np.pi)

        self._add_channel(result, f"{name}_speed", rpm, "RPM")
        self._add_channel(result, f"{name}_current", current, "A")
        self._add_channel(result, f"{name}_power", V_supply * current, "W")

    # ─── Leakage Current (Safety) ───────────────────────
    def _sim_leakage(
        self, t: np.ndarray, params: dict, name: str, result: SimulationResult
    ):
        """
        Leakage current simulation with insulation degradation over time.
        I_leak = I_base * (1 + degradation*t) + noise
        """
        I_base_ua = params.get("base_leakage_ua", 10.0)  # µA
        degradation_rate = params.get("degradation_rate", 0.001)  # per second
        limit_ua = params.get("safety_limit_ua", 100.0)  # µA (IEC 60601)
        temp_coeff = params.get("temp_coefficient", 0.02)  # per °C

        temp_variation = 25 + 5 * np.sin(2 * np.pi * t / max(t[-1], 1) * 2)
        temp_factor = 1 + temp_coeff * (temp_variation - 25)

        leakage = I_base_ua * (1 + degradation_rate * t) * temp_factor
        noise = np.random.normal(0, I_base_ua * 0.05, len(t))
        leakage = np.clip(leakage + noise, 0, None)

        self._add_channel(result, f"{name}_leakage_current", leakage, "µA")
        self._add_channel(result, f"{name}_temperature", temp_variation, "°C")

        if np.max(leakage) > limit_ua:
            result.warnings.append(
                f"⚠️ SAFETY VIOLATION: Leakage current exceeds {limit_ua}µA (peak: {np.max(leakage):.1f}µA)"
            )
        result.metrics[f"{name}_peak_leakage_ua"] = round(float(np.max(leakage)), 2)
        result.metrics[f"{name}_compliant"] = (
            1.0 if np.max(leakage) <= limit_ua else 0.0
        )

    # ─── Sensor Noise ───────────────────────────────────
    def _sim_sensor(
        self, t: np.ndarray, params: dict, name: str, result: SimulationResult
    ):
        """Generic sensor with response time, noise, and saturation."""
        true_value = params.get("true_value", 98.0)
        response_time = params.get("response_time_s", 0.5)
        noise_std = params.get("noise_std", 0.3)
        saturation_max = params.get("saturation_max", 100.0)
        saturation_min = params.get("saturation_min", 0.0)

        # Step response
        reading = true_value * (1 - np.exp(-t / response_time))
        noise = np.random.normal(0, noise_std, len(t))
        reading = np.clip(reading + noise, saturation_min, saturation_max)

        self._add_channel(result, f"{name}_reading", reading, params.get("unit", ""))
        result.metrics[f"{name}_settled_value"] = round(float(reading[-1]), 2)
        result.metrics[f"{name}_settling_time_s"] = round(5 * response_time, 3)
